const VIDEOS = {
  fiverrHow: { id: "Npta6zk_Eu0", title: "How Fiverr Works | Fiverr", seconds: 60 },
  fiverrWhat: { id: "eJKtp7z8MbA", title: "What is Fiverr | Explained in 2 min", seconds: 142 },
  fiverrBuy: { id: "x1oKjrb6uFo", title: "How to Place an Order on Fiverr as a Buyer", seconds: 267 },
  fiverrFee: { id: "aopf65uIpx8", title: "How Much Does Fiverr Take", seconds: 226 },
  fiverrOrder: { id: "3g7wHjzeU8Q", title: "How Does Fiverr Work for Sellers | The Order Process", seconds: 235 },
  fiverrDeliver: { id: "RHrTTsrWY9c", title: "How to Deliver Orders Correctly on Fiverr", seconds: 78 },
  fiverrTimeRev: { id: "fX0LaGSUdFM", title: "How to Add Delivery Time and Revisions to a Fiverr Gig", seconds: 100 },
  fiverrRevFix: { id: "7oTtMjjhRR0", title: "How to Add Revisions to Fiverr Orders", seconds: 110 },
  fiverrReview: { id: "FgWgnZzP3A0", title: "How to respond to a client review on Fiverr", seconds: 111 },
  fiverrTerms: { id: "3ns7nZhXUMg", title: "Decoding Fiverr's Terms of Service", seconds: 140 },
  fiverrBan: { id: "z8OVxUHpAVQ", title: "Fiverr account restriction: no fake orders or reviews", seconds: 110 },
  niche: { id: "i-fn0I1MKME", title: "How to choose a freelance niche", seconds: 198 },
  valueProp: { id: "y91FzT6CtUI", title: "How To Write A Value Proposition", seconds: 173 },
  research: { id: "kEl22YHnU8g", title: "Freelance Market Research", seconds: 62 },
  practice: { id: "f2O6mQkFiiw", title: "How to practice effectively — TED-Ed", seconds: 289 },
  canvaBeginner: { id: "V9LtRF6EbyY", title: "Canva for Beginners: Opening Canva", seconds: 238 },
  canvaSocial: { id: "p-QgpcN4Gd4", title: "How to Use Canva for Social Media Templates", seconds: 167 },
  canvaAlign: { id: "9xAyC26LPmI", title: "How To Align And Position Objects In Canva", seconds: 129 },
  canvaExport: { id: "GTp1NARyqBE", title: "Canva — How to Export Image", seconds: 132 },
  canvaMistakes: { id: "rctxUW9x85k", title: "10 Beginner Mistakes to Avoid in Canva", seconds: 155 },
  fileFormats: { id: "KLtjcf42Iwo", title: "File Formats: When to Use JPG, PNG, TIFF, PDF, EPS or SVG", seconds: 107 },
  contrast: { id: "X55zsNZ9xow", title: "The Visual Principle of Contrast in UI Design", seconds: 134 },
  hierarchy: { id: "ihCYnw4iUfg", title: "60 Second Design Tips — Hierarchy", seconds: 57 },
  brand: { id: "sO4te2QNsHY", title: "What Is Branding? 4 Minute Crash Course", seconds: 229 },
  consistency: { id: "y2N5ArBKQ4g", title: "Visual Consistency — Two Minute Tuesday", seconds: 153 },
  igSize: { id: "rdu7qduz7Qg", title: "How to Resize Photo for Instagram Post in Canva", seconds: 99 },
  clientQs: { id: "cJrpeLgW_Wc", title: "10 Questions to Ask a Client Before Creating a Design Brief", seconds: 221 },
  qc: { id: "UOWXojjKyHE", title: "Design Review Checklist", seconds: 119 },
  proofread: { id: "bTn-do2WWcY", title: "Plain Language Tips: Proofreading", seconds: 88 },
  files: { id: "or9fDxUXO4k", title: "How to Organize your Design Files", seconds: 149 },
  portfolio: { id: "BIhqWN40g_o", title: "How To Make A Design Portfolio With No Experience", seconds: 216 },
  packages: { id: "X8WNuvdQVEU", title: "How to Create Fiverr Gig Packages", seconds: 78 },
  scope: { id: "NXw0bvvYWYo", title: "What is Project Scope? Project Management in Under 5", seconds: 210 },
  extras: { id: "VksuvOJdqS4", title: "How To Create Gig Extras on Fiverr", seconds: 280 },
  sourceFiles: { id: "vMGWnM6Sk8o", title: "Always Make Sure To Get Your Source Files", seconds: 230 },
  pricing: { id: "jE53O1PzmNU", title: "Pricing Design Work & Creativity — Stop Charging Hourly", seconds: 158 },
  headshot: { id: "rgj-w_iyTGM", title: "Pro Headshots with your Smartphone in 6 Easy Steps", seconds: 150 },
  gigTitle: { id: "7MSP2vl1gnc", title: "How to Write a Fiverr Gig Title", seconds: 109 },
  gigDesc: { id: "gydahRzquWk", title: "How to Write a Fiverr Gig Description", seconds: 81 },
  profileBio: { id: "8o0x-ogs88k", title: "How To Write A Fiverr Profile Description", seconds: 106 },
  profile: { id: "E7HdHkg-8PE", title: "How To Make A Fiverr Profile", seconds: 168 },
  verify: { id: "RkHGFlATSj8", title: "How to Verify Account in Fiverr", seconds: 96 },
  requirements: { id: "BdanUQJCLrI", title: "How To Add Gig Requirements Questions On Fiverr", seconds: 153 },
  gigSeo: { id: "OQ_KMqYjPDM", title: "How to Optimize Fiverr Gig SEO", seconds: 62 },
  seoTitles: { id: "B4gZNuVJtmA", title: "How do I write optimized page titles? | Learn from Fiverr", seconds: 211 },
  gigThumb: { id: "0O-7S2i1luw", title: "How to Make a Thumbnail for Fiverr Gig on Canva", seconds: 210 },
  gigVideo: { id: "AgRVnl_xjXI", title: "How To Add a Video On Fiverr Gig", seconds: 56 },
  customOffer: { id: "5Aye_fPrNXU", title: "How to send a custom offer on Fiverr", seconds: 132 },
  firstReply: { id: "pvQ0LfuWGho", title: "How to reply to a Fiverr message professionally", seconds: 82 },
  difficult: { id: "jck3RFN0AvM", title: "Difficult Clients? A Freelancer's Guide", seconds: 137 },
  clientTalk: { id: "b4qNkTRJrl0", title: "How to Communicate with Clients Like a Pro", seconds: 216 },
  brief: { id: "XxZETOZiQK8", title: "7 Things That Go Into A Good Creative Brief", seconds: 188 },
  timeTrack: { id: "WOsK8YUv6mM", title: "Freelance Time Tracking", seconds: 264 },
  notify: { id: "qhEFw6AvjKg", title: "How To Turn On Fiverr Account Notification", seconds: 75 },
  shareGig: { id: "nTcNEMCHlhQ", title: "How To Share Gigs In Fiverr", seconds: 132 },
  linkedin: { id: "0Tv64d61Ibc", title: "How To Add a Portfolio Link on LinkedIn", seconds: 85 },
  analytics: { id: "HZJPi1zthkg", title: "How To Check Fiverr Analytics", seconds: 148 },
  ytThumb: { id: "4X3efQiR6tA", title: "How To Make A YouTube Thumbnail in 3 Minutes", seconds: 201 },
  captions: { id: "f149en5WeLY", title: "How To Add Auto Captions In CapCut", seconds: 129 },
  hooks: { id: "SE0RtO3aVgI", title: "Hook people in within 3 seconds with video", seconds: 68 },
  pacing: { id: "IG683SXcal4", title: "Video Editing Pacing Tips", seconds: 200 },
  audio: { id: "ENt6dzZ2Bh0", title: "5 Ways to Adjust Audio Levels in DaVinci Resolve", seconds: 203 },
  vertical: { id: "SBJkKyylFwg", title: "Vertical/Horizontal Video Aspect Ratios, Explained", seconds: 95 },
  wpBasics: { id: "WyNnDhywU5w", title: "What is WordPress? And How Does It Work?", seconds: 218 },
  wpStart: { id: "M01nLhK4dPk", title: "WordPress Quick Start Guide", seconds: 263 },
  wpBuilder: { id: "ENDkKDtaDlA", title: "5 Best WordPress Page Builders", seconds: 275 },
  wpForm: { id: "PDGdAjmgN3Y", title: "How to Create a WordPress Contact Us Page", seconds: 167 },
  wpBackup: { id: "a2LjcRQcO8A", title: "How to Backup WordPress Database", seconds: 194 },
  responsive: { id: "S48-8wfFxPY", title: "Responsive Design Explained", seconds: 88 },
  localSeo: { id: "pUcRzziFgD4", title: "What is Local SEO? | Learn from Fiverr", seconds: 239 },
  bgRemove: { id: "4JACu-ROUWQ", title: "How to Change Background of Photo in Canva", seconds: 106 },
  productPhoto: { id: "h1tJhLTrf7c", title: "Easy Canva tutorial for product photography", seconds: 163 },
  translate: { id: "diqoKoGhhZo", title: "Translation Tips", seconds: 175 },
  slides: { id: "kK4Z2Jnl2Fg", title: "PowerPoint slide makeover, from everyday to excellent", seconds: 172 },
  graphicWhat: { id: "0BnuvEoyaZ0", title: "What Is Graphic Design?", seconds: 97 },
};

const TASK_VIDEOS = {
  "d1-find": "fiverrHow",
  "d1-fee": "fiverrFee",
  "d1-flow": "fiverrOrder",
  "d1-reviews": "fiverrReview",
  "d1-rules": "fiverrTerms",
  "d1-fake": "fiverrBan",
  "d1-pick": "niche",
  "d1-avoid": "niche",
  "d1-sentence": "valueProp",
  "d1-research": "research",
  "d1-out-service": "niche",
  "d1-out-customer": "clientQs",
  "d1-out-keyword": "gigSeo",
  "d1-out-table": "research",
  "d1-out-offer": "valueProp",
  "d2-90": "canvaBeginner",
  "d2-60a": "canvaSocial",
  "d2-30a": "graphicWhat",
  "d2-90b": "canvaSocial",
  "d2-60b": "canvaBeginner",
  "d2-30b": "canvaMistakes",
  "d2-soft": "canvaBeginner",
  "d2-files": "fileFormats",
  "d2-principles": "hierarchy",
  "d2-inputs": "clientQs",
  "d2-export": "canvaExport",
  "d2-qc": "qc",
  "d2-mistakes": "canvaMistakes",
  "d2-out-3": "canvaSocial",
  "d2-out-1": "portfolio",
  "d2-out-check": "qc",
  "d2-out-gaps": "practice",
  "d3-p1": "canvaSocial",
  "d3-p2": "canvaSocial",
  "d3-p3": "canvaSocial",
  "d3-story": "brief",
  "d3-final": "portfolio",
  "d3-label": "portfolio",
  "d3-q1": "qc",
  "d3-q2": "proofread",
  "d3-q3": "consistency",
  "d3-q4": "clientQs",
  "d3-q5": "igSize",
  "d3-q6": "canvaMistakes",
  "d3-q7": "qc",
  "d3-out-3": "portfolio",
  "d3-out-gallery": "gigThumb",
  "d3-out-source": "files",
  "d3-out-check": "qc",
  "d4-basic": "packages",
  "d4-standard": "packages",
  "d4-premium": "packages",
  "d4-scope": "scope",
  "d4-need": "requirements",
  "d4-time": "fiverrTimeRev",
  "d4-source": "sourceFiles",
  "d4-extras": "extras",
  "d4-fee": "fiverrFee",
  "d4-cover": "pricing",
  "d4-photo": "headshot",
  "d4-headline": "gigTitle",
  "d4-bio": "profileBio",
  "d4-skills": "profile",
  "d4-port": "portfolio",
  "d4-id": "verify",
  "d4-out-pack": "packages",
  "d4-out-price": "pricing",
  "d4-out-scope": "scope",
  "d4-out-profile": "profile",
  "d4-out-form": "requirements",
  "d5-title": "gigTitle",
  "d5-d1": "gigDesc",
  "d5-d2": "gigDesc",
  "d5-d3": "gigDesc",
  "d5-d4": "gigDesc",
  "d5-d5": "gigDesc",
  "d5-d6": "requirements",
  "d5-d7": "scope",
  "d5-d8": "packages",
  "d5-d9": "firstReply",
  "d5-kw-title": "gigSeo",
  "d5-kw-cat": "gigSeo",
  "d5-kw-meta": "gigSeo",
  "d5-kw-first": "seoTitles",
  "d5-kw-pack": "packages",
  "d5-kw-faq": "gigDesc",
  "d5-kw-gal": "gigThumb",
  "d5-thumb": "gigThumb",
  "d5-two": "gigThumb",
  "d5-video": "gigVideo",
  "d5-faq1": "requirements",
  "d5-faq2": "fiverrDeliver",
  "d5-faq3": "sourceFiles",
  "d5-faq4": "fiverrTimeRev",
  "d5-faq5": "scope",
  "d5-faq6": "brand",
  "d5-faq7": "customOffer",
  "d5-faq8": "firstReply",
  "d5-out-gig": "gigDesc",
  "d5-out-opt": "gigSeo",
  "d5-out-desc": "gigDesc",
  "d5-out-train": "practice",
  "d6-t1": "firstReply",
  "d6-t2": "clientQs",
  "d6-t3": "customOffer",
  "d6-t4": "clientTalk",
  "d6-t5": "clientQs",
  "d6-t6": "difficult",
  "d6-t7": "fiverrRevFix",
  "d6-t8": "fiverrDeliver",
  "d6-s1": "fiverrOrder",
  "d6-s2": "clientQs",
  "d6-s3": "difficult",
  "d6-g1": "clientQs",
  "d6-g2": "scope",
  "d6-g3": "pricing",
  "d6-g4": "customOffer",
  "d6-g5": "clientTalk",
  "d6-g6": "qc",
  "d6-g7": "fiverrRevFix",
  "d6-g8": "fiverrDeliver",
  "d6-out-t": "firstReply",
  "d6-out-s": "fiverrOrder",
  "d6-out-c": "customOffer",
  "d6-out-d": "fiverrDeliver",
  "d6-out-p": "difficult",
  "d7-e1": "brief",
  "d7-e2": "clientQs",
  "d7-e3": "timeTrack",
  "d7-e4": "scope",
  "d7-e5": "canvaSocial",
  "d7-e6": "qc",
  "d7-e7": "files",
  "d7-e8": "fiverrDeliver",
  "d7-desk": "shareGig",
  "d7-spell": "proofread",
  "d7-thumb": "gigThumb",
  "d7-pack": "packages",
  "d7-bell": "notify",
  "d7-quick": "firstReply",
  "d7-share": "shareGig",
  "d7-social": "linkedin",
  "d7-fake": "fiverrBan",
  "d7-out-gig": "shareGig",
  "d7-out-3": "portfolio",
  "d7-out-pack": "packages",
  "d7-out-pro": "profile",
  "d7-out-msg": "firstReply",
  "d7-out-del": "fiverrDeliver",
  "d7-out-sheet": "analytics",
  "d7-out-30": "practice",
};

const DAY2_BY_SERVICE = {
  canva: {
    "d2-90": "canvaBeginner",
    "d2-60a": "canvaSocial",
    "d2-soft": "canvaBeginner",
    "d2-export": "canvaExport",
    "d2-mistakes": "canvaMistakes",
  },
  thumbs: {
    "d2-90": "ytThumb",
    "d2-60a": "ytThumb",
    "d2-soft": "ytThumb",
    "d2-export": "canvaExport",
  },
  video: {
    "d2-90": "captions",
    "d2-60a": "pacing",
    "d2-soft": "captions",
    "d2-export": "vertical",
    "d2-principles": "hooks",
  },
  slides: {
    "d2-90": "slides",
    "d2-60a": "slides",
    "d2-soft": "slides",
  },
  wordpress: {
    "d2-90": "wpStart",
    "d2-60a": "wpBuilder",
    "d2-soft": "wpBasics",
    "d2-export": "wpForm",
    "d2-principles": "responsive",
  },
  photos: {
    "d2-90": "bgRemove",
    "d2-60a": "productPhoto",
    "d2-soft": "bgRemove",
    "d2-export": "fileFormats",
  },
  translate: {
    "d2-90": "translate",
    "d2-60a": "translate",
    "d2-soft": "translate",
    "d2-principles": "proofread",
  },
};

const STUDY_VIDEOS = {
  canva: ["canvaAlign", "canvaAlign", "canvaBeginner", "contrast", "hierarchy", "igSize", "brand", "igSize"],
  thumbs: ["ytThumb", "contrast", "gigThumb", "hooks", "ytThumb", "canvaExport"],
  video: ["hooks", "pacing", "captions", "audio", "pacing", "vertical", "canvaExport"],
  slides: ["slides", "contrast", "consistency", "slides", "slides", "fileFormats"],
  wordpress: ["wpBasics", "wpBuilder", "responsive", "wpForm", "wpForm", "localSeo", "wpBackup"],
  photos: ["bgRemove", "productPhoto", "consistency", "igSize", "fileFormats"],
  translate: ["translate", "clientTalk", "proofread", "translate", "proofread", "clientQs"],
};
