const VIDEOS = {
  fiverrHow: { id: "oyKw_c82-Mo", title: "فایور چیست", seconds: 343 },
  fiverrFirst: { id: "0VQLK26cVNQ", title: "گرفتن اولین پروژه در سایت فایور", seconds: 265 },
  fiverrGig: { id: "v_5tuGWcDbs", title: "روش ساختن گیگ در سایت فایور", seconds: 200 },
  fiverrProtect: { id: "g88e6xepynM", title: "چگونه مشتری تو فایور ازتون سواستفاده نکنه؟", seconds: 211 },
  fiverrVerify: { id: "Ma_65nZNvSs", title: "نحوه وریفای کردن یا احراز هویت در فایور", seconds: 160 },
  fiverrFewGigs: { id: "hAp3c6vTqcU", title: "در ابتدا چند گیگ در فایور ایجاد کنیم؟", seconds: 112 },
  fiverrFirstOrder: { id: "v5OB1xRP0pI", title: "چگونه اولین سفارش را در فایور دریافت کنم؟", seconds: 79 },
  fiverrFollow: { id: "1pfeb4G7bZg", title: "چگونه مشتری‌های گذشته را در فایور فالوآپ کنیم؟", seconds: 109 },
  fiverrStrategy: { id: "x4Y0ddO2BgM", title: "یک استراتژی عالی برای موفقیت در فایور", seconds: 81 },
  brandPromise: { id: "CZq90748obo", title: "قول برند چیست؟", seconds: 86 },
  logoBrand: { id: "8imfWnO5ODw", title: "لوگو و برندینگ چه ربطی به هم دارند", seconds: 162 },
  portfolio: { id: "AVE-bRFTUFQ", title: "چطور نمونه کار بسازیم و پروژه بیشتری بگیریم", seconds: 185 },
  practice: { id: "79KKNkhZnVs", title: "۷ روش برای یادگیری مؤثر یک زبان جدید", seconds: 282 },
  designThink: { id: "HXcLoCstLOk", title: "تفکر طراحی چیست؟", seconds: 294 },
  graphicWhat: { id: "E8UTae4L-24", title: "گرافیک چیست؟", seconds: 166 },
  canvaWhat: { id: "k_1aGerxd0M", title: "کنوا چیست؟ معرفی Canva", seconds: 211 },
  canvaSignup: { id: "qN9PRG4fwl4", title: "نصب کنوا و ثبت‌نام در Canva", seconds: 206 },
  canvaEnv: { id: "FgilIxkRXqA", title: "آموزش محیط کنوا و شروع طراحی", seconds: 310 },
  canvaExport: { id: "133HzNHPplk", title: "خروجی گرفتن از کنوا", seconds: 233 },
  canvaResize: { id: "vix5L4aa0TU", title: "تغییر سایز در کنوا؛ پست به استوری", seconds: 74 },
  canvaBg: { id: "XztPZfpJlb8", title: "حذف پس‌زمینه در کنوا", seconds: 205 },
  canvaTemplate: { id: "UYAhmE2FIvo", title: "طراحی با قالب‌های آماده کنوا", seconds: 215 },
  canvaPhone: { id: "TQSzHwd6Nxo", title: "آموزش کنوا با گوشی", seconds: 267 },
  canvaFont: { id: "onXPtX32J1k", title: "فونت و اعداد فارسی در کنوا رایگان", seconds: 60 },
  canvaType: { id: "WTMcV9fZ-zs", title: "تایپوگرافی حرفه‌ای در Canva", seconds: 232 },
  canvaSlides: { id: "4DtygeZRj6I", title: "ساخت اسلاید با موبایل در کنوا", seconds: 220 },
  canvaShadow: { id: "nTuAMoj0goI", title: "سایه‌گذاری در کنوا", seconds: 117 },
  colorTheory: { id: "GYYm19-I97c", title: "مبانی رنگ و رنگ‌شناسی", seconds: 225 },
  typeVisual: { id: "XeKDlADQbQc", title: "عناصر بصری گرافیک: تایپوگرافی", seconds: 311 },
  fileFormats: { id: "ea7JuJ6luyk", title: "تبدیل فرمت عکس؛ JPG، PNG، PDF", seconds: 264 },
  ytThumb: { id: "FT8Rrgw0pzs", title: "ساخت تامنیل جذاب با گوشی در کمتر از ۴ دقیقه", seconds: 278 },
  ytThumbCanva: { id: "qQoecHxdJW4", title: "آموزش ساخت تامنیل با Canva", seconds: 292 },
  captions: { id: "hlJ3Rn1a3SU", title: "زیرنویس خودکار در کپ‌کات", seconds: 187 },
  captionsFa: { id: "UYFSZ16Q_hM", title: "زیرنویس فارسی در کپ‌کات", seconds: 114 },
  hooks: { id: "kvvm3nGNuXk", title: "قلاب ریلز اینستاگرام", seconds: 118 },
  hooksLong: { id: "wTUaFU-WFo4", title: "فرمول ساخت هوک قوی برای یوتیوب و اینستا", seconds: 292 },
  pacing: { id: "YXXzaX9cACI", title: "ریتم در تدوین", seconds: 191 },
  audio: { id: "otd97URsjh0", title: "ضبط صدا و افکت در کپ‌کات", seconds: 284 },
  vertical: { id: "0nN-8UJyPWI", title: "تبدیل ویدیو افقی به عمودی با کپ‌کات", seconds: 225 },
  wpWhat: { id: "x89UximuSXo", title: "وردپرس چیست؟", seconds: 102 },
  wpLogin: { id: "n1gnmGIuGWI", title: "نحوه ورود به پیشخوان وردپرس", seconds: 176 },
  wpPage: { id: "r2WE14IoALo", title: "ساخت صفحه جدید در وردپرس", seconds: 79 },
  wpBuilder: { id: "kryBcwBEcy4", title: "المنتور چیست؟ صفحه‌ساز وردپرس", seconds: 144 },
  wpForm: { id: "KZl1uSX3LEo", title: "آموزش افزونه فرم تماس وردپرس", seconds: 289 },
  wpBackup: { id: "9bjkZx1jdDw", title: "خروجی گرفتن از اطلاعات وردپرس", seconds: 270 },
  responsive: { id: "IsfdJr593HE", title: "سایت ریسپانسیو یا واکنش‌گرا چیست؟", seconds: 209 },
  localSeo: { id: "1H9_iAx1Ed8", title: "سئو محلی چیست و چه کاربردی دارد؟", seconds: 130 },
  productPhoto: { id: "9vNpyxmpDug", title: "عکس‌برداری از محصولات برای فروشگاه", seconds: 156 },
  translate: { id: "GKbQZshvXHw", title: "پنج نکته برای بهبود ترجمه انگلیسی به فارسی", seconds: 310 },
  slides: { id: "LD3kcevMvRE", title: "آموزش اسلاید مستر در پاورپوینت", seconds: 217 },
  slidesNew: { id: "P3UevkwGTIk", title: "ایجاد اسلاید جدید در پاورپوینت", seconds: 216 },
  pricing: { id: "HNmhYWgTNBM", title: "برای پروژه‌ها چقدر قیمت بدهیم؟", seconds: 323 },
  headshot: { id: "1e9aksg38J4", title: "آموزش گرفتن عکس پروفایل جذاب", seconds: 316 },
  clientFirst: { id: "qPZOk7DjUs0", title: "ارتباط با مشتری در اولین برخورد", seconds: 106 },
  difficult: { id: "HjQac9DfGD0", title: "چطور با مشتری سخت‌گیر مذاکره کنیم؟", seconds: 296 },
  linkedin: { id: "2KWTEkhZeCs", title: "آموزش ساخت اکانت و پروفایل لینکدین", seconds: 190 },
};

const TASK_VIDEOS = {
  "d1-find": "fiverrFirst",
  "d1-fee": "fiverrHow",
  "d1-flow": "fiverrFirstOrder",
  "d1-reviews": "fiverrFollow",
  "d1-rules": "fiverrProtect",
  "d1-fake": "fiverrProtect",
  "d1-pick": "fiverrFewGigs",
  "d1-avoid": "fiverrFewGigs",
  "d1-sentence": "brandPromise",
  "d1-research": "portfolio",
  "d1-out-service": "fiverrFewGigs",
  "d1-out-customer": "clientFirst",
  "d1-out-keyword": "fiverrGig",
  "d1-out-table": "portfolio",
  "d1-out-offer": "brandPromise",
  "d2-90": "canvaWhat",
  "d2-60a": "canvaEnv",
  "d2-30a": "graphicWhat",
  "d2-90b": "canvaTemplate",
  "d2-60b": "canvaPhone",
  "d2-30b": "canvaFont",
  "d2-soft": "canvaSignup",
  "d2-files": "fileFormats",
  "d2-principles": "typeVisual",
  "d2-inputs": "clientFirst",
  "d2-export": "canvaExport",
  "d2-qc": "portfolio",
  "d2-mistakes": "canvaFont",
  "d2-out-3": "canvaEnv",
  "d2-out-1": "portfolio",
  "d2-out-check": "portfolio",
  "d2-out-gaps": "practice",
  "d3-p1": "canvaTemplate",
  "d3-p2": "canvaPhone",
  "d3-p3": "canvaEnv",
  "d3-story": "designThink",
  "d3-final": "portfolio",
  "d3-label": "portfolio",
  "d3-q1": "portfolio",
  "d3-q2": "translate",
  "d3-q3": "logoBrand",
  "d3-q4": "clientFirst",
  "d3-q5": "canvaResize",
  "d3-q6": "canvaFont",
  "d3-q7": "portfolio",
  "d3-out-3": "portfolio",
  "d3-out-gallery": "ytThumbCanva",
  "d3-out-source": "canvaExport",
  "d3-out-check": "portfolio",
  "d4-basic": "fiverrGig",
  "d4-standard": "fiverrGig",
  "d4-premium": "fiverrGig",
  "d4-scope": "fiverrProtect",
  "d4-need": "fiverrProtect",
  "d4-time": "fiverrProtect",
  "d4-source": "canvaExport",
  "d4-extras": "fiverrGig",
  "d4-fee": "fiverrHow",
  "d4-cover": "pricing",
  "d4-photo": "headshot",
  "d4-headline": "fiverrGig",
  "d4-bio": "fiverrStrategy",
  "d4-skills": "fiverrFewGigs",
  "d4-port": "portfolio",
  "d4-id": "fiverrVerify",
  "d4-out-pack": "fiverrGig",
  "d4-out-price": "pricing",
  "d4-out-scope": "fiverrProtect",
  "d4-out-profile": "fiverrVerify",
  "d4-out-form": "fiverrProtect",
  "d5-title": "fiverrGig",
  "d5-d1": "fiverrGig",
  "d5-d2": "fiverrGig",
  "d5-d3": "fiverrGig",
  "d5-d4": "fiverrStrategy",
  "d5-d5": "fiverrGig",
  "d5-d6": "fiverrProtect",
  "d5-d7": "fiverrProtect",
  "d5-d8": "fiverrGig",
  "d5-d9": "clientFirst",
  "d5-kw-title": "fiverrGig",
  "d5-kw-cat": "fiverrFewGigs",
  "d5-kw-meta": "fiverrGig",
  "d5-kw-first": "fiverrGig",
  "d5-kw-pack": "fiverrGig",
  "d5-kw-faq": "fiverrProtect",
  "d5-kw-gal": "ytThumbCanva",
  "d5-thumb": "ytThumbCanva",
  "d5-two": "ytThumb",
  "d5-video": "fiverrGig",
  "d5-faq1": "fiverrProtect",
  "d5-faq2": "canvaExport",
  "d5-faq3": "canvaExport",
  "d5-faq4": "fiverrProtect",
  "d5-faq5": "fiverrProtect",
  "d5-faq6": "logoBrand",
  "d5-faq7": "fiverrGig",
  "d5-faq8": "clientFirst",
  "d5-out-gig": "fiverrGig",
  "d5-out-opt": "fiverrGig",
  "d5-out-desc": "fiverrGig",
  "d5-out-train": "practice",
  "d6-t1": "clientFirst",
  "d6-t2": "clientFirst",
  "d6-t3": "fiverrProtect",
  "d6-t4": "clientFirst",
  "d6-t5": "clientFirst",
  "d6-t6": "difficult",
  "d6-t7": "fiverrProtect",
  "d6-t8": "fiverrFollow",
  "d6-s1": "fiverrFirstOrder",
  "d6-s2": "clientFirst",
  "d6-s3": "difficult",
  "d6-g1": "clientFirst",
  "d6-g2": "fiverrProtect",
  "d6-g3": "pricing",
  "d6-g4": "fiverrProtect",
  "d6-g5": "clientFirst",
  "d6-g6": "portfolio",
  "d6-g7": "fiverrProtect",
  "d6-g8": "fiverrFollow",
  "d6-out-t": "clientFirst",
  "d6-out-s": "fiverrFirstOrder",
  "d6-out-c": "fiverrProtect",
  "d6-out-d": "fiverrFollow",
  "d6-out-p": "difficult",
  "d7-e1": "designThink",
  "d7-e2": "clientFirst",
  "d7-e3": "pricing",
  "d7-e4": "fiverrProtect",
  "d7-e5": "canvaEnv",
  "d7-e6": "portfolio",
  "d7-e7": "canvaExport",
  "d7-e8": "fiverrFollow",
  "d7-desk": "fiverrFollow",
  "d7-spell": "translate",
  "d7-thumb": "ytThumbCanva",
  "d7-pack": "fiverrGig",
  "d7-bell": "fiverrFirstOrder",
  "d7-quick": "clientFirst",
  "d7-share": "fiverrFollow",
  "d7-social": "linkedin",
  "d7-fake": "fiverrProtect",
  "d7-out-gig": "fiverrFollow",
  "d7-out-3": "portfolio",
  "d7-out-pack": "fiverrGig",
  "d7-out-pro": "fiverrVerify",
  "d7-out-msg": "clientFirst",
  "d7-out-del": "fiverrFollow",
  "d7-out-sheet": "fiverrStrategy",
  "d7-out-30": "practice",
};

const DAY2_BY_SERVICE = {
  canva: {
    "d2-90": "canvaWhat",
    "d2-60a": "canvaEnv",
    "d2-soft": "canvaSignup",
    "d2-export": "canvaExport",
    "d2-mistakes": "canvaFont",
  },
  thumbs: {
    "d2-90": "ytThumb",
    "d2-60a": "ytThumbCanva",
    "d2-soft": "canvaPhone",
    "d2-export": "canvaExport",
  },
  video: {
    "d2-90": "captionsFa",
    "d2-60a": "pacing",
    "d2-soft": "captions",
    "d2-export": "vertical",
    "d2-principles": "hooks",
  },
  slides: {
    "d2-90": "slides",
    "d2-60a": "slidesNew",
    "d2-soft": "canvaSlides",
  },
  wordpress: {
    "d2-90": "wpLogin",
    "d2-60a": "wpBuilder",
    "d2-soft": "wpWhat",
    "d2-export": "wpForm",
    "d2-principles": "responsive",
  },
  photos: {
    "d2-90": "canvaBg",
    "d2-60a": "productPhoto",
    "d2-soft": "canvaBg",
    "d2-export": "fileFormats",
  },
  translate: {
    "d2-90": "translate",
    "d2-60a": "translate",
    "d2-soft": "captionsFa",
    "d2-principles": "practice",
  },
};

const STUDY_VIDEOS = {
  canva: ["canvaEnv", "canvaEnv", "canvaType", "colorTheory", "typeVisual", "canvaResize", "logoBrand", "canvaResize"],
  thumbs: ["ytThumb", "colorTheory", "ytThumbCanva", "hooks", "ytThumb", "canvaExport"],
  video: ["hooks", "pacing", "captionsFa", "audio", "pacing", "vertical", "canvaExport"],
  slides: ["slidesNew", "colorTheory", "logoBrand", "slides", "canvaSlides", "fileFormats"],
  wordpress: ["wpWhat", "wpBuilder", "responsive", "wpForm", "wpPage", "localSeo", "wpBackup"],
  photos: ["canvaBg", "productPhoto", "logoBrand", "canvaResize", "fileFormats"],
  translate: ["translate", "clientFirst", "practice", "translate", "captionsFa", "clientFirst"],
};
